### ISSUE TITLE
Ping command doesn't work.

### ISSUE THREAD

**Issue by unixfox** [drizzt/vps2arch#20] opened 2016-08-15 14:29 UTC
Hi !

I used this script on a Debian 7.0 OpenVZ machine and it works !

I've a problem when I use the command `ping` it returns me an error:
````
[root@box ~]# ping 8.8.8.8
ping: 8.8.8.8: Address family for hostname not supported
````

I made some research: reconfig *netctl*, [disable IPv6,](https://wiki.archlinux.org/index.php/IPv6#Disable_functionality), searching about this error on Google. 
I can't find a solution to my problem.

Apart from that everything works well with Internet: I can use curl, wget, pacman, etc.

Some informations about my VPS:
- Don't support IPv6
- Arch : x86_64
- Netctl config:
````
Interface=venet0
Connection=ethernet
IP=static
Address=(127.0.0.2/32 88.198.xxx.xx/32 88.198.xxx.xx/32)
Routes=(0.0.0.0/0)
DNS=('213.133.100.100' '213.133.98.98' '213.133.99.99' '8.8.8.8')
````

**Comment by drizzt** [comment] 2016-08-16 21:53
Did ping work with original Debian 7.0?

**Comment by drizzt** [comment] 2016-08-16 21:54
or you can try to use `ping -4 8.8.8.8`

**Comment by unixfox** [comment] 2016-08-16 22:51
> Did ping work with original Debian 7.0?

Yes sure.

> or you can try to use ping -4 8.8.8.8

It returns me the same error:
````
ping: socket: Address family not supported by protocol
````

**Comment by ljxc** [comment] 2016-08-24 04:51
A temporary solution:
Downgrade iputils.
https://archive.archlinux.org/packages/i/iputils/iputils-20150815.1c59920-3-x86_64.pkg.tar.xz  works fine.
It seems to be an OVZ-only problem.

**Comment by unixfox** [comment] 2016-08-24 16:15
@ljxc Thank you, it works !

**Comment by drizzt** [comment] 2016-08-24 16:56
iputils problem already fixed on git, closing.
thank you @ljxc for the root cause

**Closed by drizzt** 2016-08-24 16:56 UTC
